### ISSUE TITLE
Proposal: Add Dependabot Support for Dependency Management

### ISSUE THREAD

**Issue by Jasrags** [GoMudEngine/GoMud#333]
**Summary**
Enable [Dependabot](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically) in the repository to automatically monitor and manage dependency updates via pull requests.

**Why It’s Useful**
    Keeps dependencies up to date with the latest patches and security fixes
    Reduces manual work and helps maintain long-term project health
    Alerts on known vulnerabilities in dependencies via GitHub’s security advisories

Proposed config file `github/dependabot.yml`
```
version: 2
updates:
  - package-ecosystem: "gomod" 
    directory: "/"
    schedule:
      interval: "weekly"
```
